repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0 # Use the desired version
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.282
    hooks:
      - id: ruff
        args: [ '--ignore=E501' ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1 # Use the desired version
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML , types-jsonschema]

