[tool.poetry]
name = "hyperiontf"
version = "0.7.05"
description = "Hyperion Testing Framework"
authors = ["Oleksiy Bondar <bondaroleksiyandriyovich@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]

[tool.poetry.dependencies]
requests="^2.33.1"
python = "^3.11"
jsonschema = "^4.26.0"
selenium = "^4.43.0"
Appium-Python-Client = "^5.3.1"
playwright = "^1.59.0"
webdriver_manager="^4.0.2"
ply="^3.11"
opencv-python="^4.13.0.92"
opencv-python-headless="^4.13.0.92"
opencv-contrib-python="^4.13.0.92"
ptyprocess="^0.7.0"
paramiko="^5.0.0"
lxml="^6.1.0"
pyyaml="^6.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
