name: Hyperion Test Framework Workflow

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  style-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install style check dependencies
        run: pip install mypy black

      - name: Run MyPy for type checking
        run: mypy src/ tests/**/*.py --non-interactive --install-types

      - name: Run Black for code formatting
        run: black --check src/ tests/**/*.py

      - name: Run Ruff for additional style checks
        run: |

  web-test-execution:
    needs: style-checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Edge
        uses: browser-actions/setup-edge@v1

      - name: Install test dependencies
        run: |
          cd tests
          sh ./install_web_dependencies.sh

      - name: Extend PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src:$(pwd)/tests" >> $GITHUB_ENV

      - name: Run Common and Web tests
        run: |
            cd tests
            pytest common/ web/

      - name: Upload logs as artifact
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: ${{ github.workspace }}/tests/logs/
          retention-days: 7

  build-check:
    needs: web-test-execution
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Build with Poetry (without publishing)
        run: poetry build
